useTabs: true
singleQuote: false
trailingComma: all
printWidth: 140
quoteProps: as-needed

# Add from Svelte
plugins:
  - prettier-plugin-svelte
  - prettier-plugin-css-order
overrides:
  - files: "*.svelte"
    options:
      parser: svelte
